spring:
  cloud:
    stream:
      kafka:
        binder: {brokers: my-cluster-kafka-brokers.softwaretesting-dev, zk-nodes: my-cluster-zookeeper-nodes.softwaretesting-dev}
      bindings:
        output: {destination: topic-jhipster}
  jackson:
    serialization: {indent-output: true}
  sleuth:
    sampler: {probability: 1}
  mail: {port: 25, host: localhost}
  zipkin:
    base-url: http://localhost:9411
    locator:
      discovery: {enabled: true}
    enabled: false
  couchbase:
    bucket: {password: password1234, name: default}
    bootstrap-hosts: cb-example.testingjenkinss-dev
  profiles:
    include: [swagger]
    active: dev
  messages: {cache-duration: PT1S}
  devtools:
    livereload: {enabled: false}
    restart: {enabled: true}
  thymeleaf: {cache: false}
server: {port: 8080}
jhipster:
  cache:
    hazelcast:
      management-center: {update-interval: 3, enabled: false, url: 'http://localhost:8180/mancenter'}
      time-to-live-seconds: 3600
      backup-count: 1
  security:
    authentication:
      jwt: {base64-secret: YTdhOTBhNzFmNzJhY2QxM2YyODE1ZGRmOWI0N2E1NmUxYWUyMDRiYzQ4YzIzNmM2YWJhOTNhMWQ5ZDk4OWUyOWEyNzcyYjQ0YTAyMjIyNjRmNjYwYTRiYjQ5MzMyNTBiZmVlODIxMmU5OThhNWZmNjAyYjA2NTZlMjJhMWZkNGU=,
        token-validity-in-seconds: 86400, token-validity-in-seconds-for-remember-me: 2592000}
  mail: {base-url: 'http://127.0.0.1:8080', from: fire1@localhost}
  http: {version: V_1_1}
  logging:
    logstash: {port: 5000, queue-size: 512, host: localhost, enabled: false}
  metrics:
    logs: {report-frequency: 60, enabled: false}
opentracing:
  spring:
    cloud:
      websocket: {enabled: 'false'}
logging:
  level: {ROOT: DEBUG, com.infy.tele: DEBUG, io.github.jhipster: DEBUG}
