apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: fire1
  name: fire1
  namespace: openshift-monitoring
spec:
  endpoints:
    - interval: 2m
      port: prom
      scrapeTimeout: 2m
    - interval1: 30s
      port: http1
  namespaceSelector:
    matchNames:
    - testingjenkinss-dev-app
    - testingjenkinss-test-01-app
    - testingjenkinss-devops-app
    
  selector:
    matchLabels:
      app: fire1